### ISSUE TITLE
Lightmod fails silently at startup - JDK bug

### ISSUE THREAD

**Issue by alpyne** [oakes/Lightmod#10]
Really excited to try this, but fell at the very first hurdle - the app wouldn't start. 
For a few seconds I could see the app name appear on the menubar, then it disappeared.
After a bit of searching I narrowed it down to this OpenJDK bug:

https://bugs.openjdk.java.net/browse/JDK-8089900

which is marked Fixed in (as yet unreleased) version 10.

In short, the mentioned workaround (Open "Font Book", choose File > Restore Standard Fonts...) worked for me.

Leaving this as a quick note in case anyone else runs into this between now and whenever Lightmod/Clojure move to Java 10.

**Comment by oakes** [comment]
Ah interesting, thank you for posting this. What version of OS X are you using? Doesn't seem to happen on the latest, but the ticket mentions 10.9 and 10.10

**Comment by alpyne** [comment]
10.12.6 (Sierra)

**Comment by oakes** [comment]
Lightmod now uses JDK 11 so i'll close this.
