### ISSUE TITLE
Adding dependencies

### ISSUE THREAD

**Issue by achikin** [oakes/Lightmod#11]
How can I add dependencies to my Lightmod project?

**Comment by oakes** [comment]
Currently you have to export your project if you want the flexibility of adding new dependencies. The other option, if you want to continue using Lightmod, is to build your own copy of it with the dependency added. It's pretty simple: clone this repo, add whatever you want to `deps.edn`, and then run `boot build`. Then you can run it with `java -jar target/project.jar`. Kind of a roundabout solution but currently those are the two options.
