### ISSUE TITLE
Name Dialog too small to type in

### ISSUE THREAD

**Issue by jbwyatt4** [oakes/Lightmod#15]
Hi,

New to Lightmod. Just opened this up on KDE Manjaro.

When I get the selection for the 6 different templates. Clicking on one of them causes a window too small to type in to be displayed.

https://i.imgur.com/hBvjmMz.png

**Comment by oakes** [comment]
Interesting, it doesn't happen in ubuntu so maybe it's a KDE specific issue. Did you run it via the installer or the jar file?

**Comment by jbwyatt4** [comment]
Jar. 1.3.0.

**Comment by oakes** [comment]
Can you try [version 1.4.0](https://github.com/oakes/Lightmod/releases/tag/1.4.0)? I'm not entirely sure it fixes the problem but i did update javafx so it may help.

**Comment by jbwyatt4** [comment]
Tested 1.4.1. The field shows perfectly. Thank you for your work.

Tested on both OpenJDK 11 and 12. The KDE issue was in both 11 and 12.

This is also fixed an issue where simply moving the mouse over one of the buttons crashed the application in OpenJDK 12 (11 was okay).
