### ISSUE TITLE
Stupid question. How do I run?

### ISSUE THREAD

**Issue by interstar** [oakes/Lightmod#17]
This is possibly the stupidest question ever. 

But I installed the .deb package in Ubuntu.

Now, how do I run lightmod?

There doesn't seem to be a program called lightmod or any other variation of the name I can think of.

**Comment by oakes** [comment]
Not a dumb question, i think some linux distros don't automatically add it to their program launchers. It should install into the `/opt` folder. If you run `/opt/Lightmod/Lightmod` on the command line i believe that will launch it.

**Comment by interstar** [comment]
OK. Yep, it's there.

Works fine.  Cheers

BTW : And this looks a very exciting project. Thanks for that
