### ISSUE TITLE
First tests. Problems with javascript from JAR

### ISSUE THREAD

**Issue by interstar** [oakes/Lightmod#18]
I'm trying out LightMod, which looks very good. And very close to something I can use.

The basic counter example works for me.

When I export it as a boot project I can run that fine, too.

But when I try to ```boot build``` it to get a stand-alone JAR file, it fails.

Running the jar file shows nothing on the command line, and it's not clear what port to try to access the web site on.

So I changes the server.clj file in the example, so that it now says ```(run-server {:port 4545})``` and I rebuilt the JAR.

When try to access localhost:4545 I just get "Firefox can't find the file at http://localhost:4545/."

When I try to access localhost:4545/index.html I see the html in index.html. But the Javascript fails.

```

TypeError: Hh is undefinedmain.js:354:405
    Wh http://localhost:4545/main.js:354
    Zh http://localhost:4545/main.js:357
    Bi http://localhost:4545/main.js:370
    yi http://localhost:4545/main.js:370
    <anonymous> http://localhost:4545/main.js:373
    Gi http://localhost:4545/main.js:372
    <anonymous> http://localhost:4545/main.js:373
    <anonymous> http://localhost:4545/main.js:374

```

**Comment by oakes** [comment]
Can you try lightmod 1.4.1 (the jar file version)? It is much more recent and the export feature now creates a project buildable with the clojure CLI tool. In the project, you can build the jar with `clj -A:prod:app` (the readme says `clj -A:prod` but that is wrong...i updated the text just now). The Boot template may be broken at this point.

Note that it still doesn't print anything out and runs on a random port by default, so you need to do the same thing you did to hard code a port. So if you do port 3000 it'll run on `http://localhost:3000/index.html`. I'll try to improve the way this works in the future.

**Comment by interstar** [comment]
OK.

That works. Thanks.

I notice it's downloading a lot of stuff, including Leiningen. And it creates a project.clj file. Does that mean we could build the uberjar with Leiningen too?

**Comment by oakes** [comment]
Leiningen won't be able to build it out of the box, because all the deps are specified in the `deps.edn` file which it can't read. However if you configure the project.clj file using [lein-tools-deps](https://github.com/RickMoynihan/lein-tools-deps) you may be able to use lein.

**Comment by oakes** [comment]
FYI I just released version 1.4.2 so the native packages (including .deb and .AppImage) are now up to date with the latest verison.

**Comment by interstar** [comment]
Cool. Thanks. 

I'm managing to work on a, fairly small and simple, but nevertheless useful, app inside LightMod. So I'm very excited by this.

**Comment by interstar** [comment]
One final question in this thread. 

I can do `clj -A:prod:app` to build the uberjar. And that works.

But how can I just run this exported project for development with clj?

When I try 

```clj -m my.namespace ```

I get 

```
Syntax error (FileNotFoundException) compiling at (clj_ts/server.clj:1:1).
Could not locate org/httpkit/server__init.class, org/httpkit/server.clj or org/httpkit/server.cljc on classpath.

```

(I'm not used to using clj, I've always worked with Leiningen in the past)

**Comment by oakes** [comment]
That would be `clj -A:dev:app`. If you forget, they are listed in the readme of the exported project 

On Tue, Dec 24, 2019, at 2:47 AM, phil jones wrote:
> One final question in this thread.

> I can do `clj -A:prod:app` to build the uberjar. And that works.

> But how can I just run this exported project for development with clj?

> When I try

> `clj -m my.namespace`

> I get

> `Syntax error (FileNotFoundException) compiling at (clj_ts/server.clj:1:1).
Could not locate org/httpkit/server__init.class, org/httpkit/server.clj or org/httpkit/server.cljc on classpath.

`

**Comment by interstar** [comment]
Great, works a treat.

**Comment by interstar** [comment]
Though although it seems to be installing FigWheel, I'm not getting live updating when I save changed files from emacs. Should I be?

**Comment by oakes** [comment]
Darn, it looks like i messed up the config there. A quick fix is to edit `dev.cljs.edn`  and change the `:main` option from `*.dev` to `*.client`. I'll cut a new release today that fixes it.

**Comment by oakes** [comment]
Another option is to move `resources/.../dev.cljs` to `src/.../dev.cljs` which is probably how i will fix it in the next version.

**Comment by interstar** [comment]
Cool. Yep, that works.

Many thanks again.
