### ISSUE TITLE
Segfault (SIGSEV) on Arch Linux

### ISSUE THREAD

**Issue by RGrun** [oakes/Lightmod#4]
Hi there, 

I'm trying to run this through the .jar file on Arch Linux, but it now crashes immediately with the following error every time I launch it, a few seconds after the GUI appears:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ff463de411b, pid=5840, tid=0x00007ff471c56700
#
# JRE version: OpenJDK Runtime Environment (8.0_144-b01) (build 1.8.0_144-b01)
# Java VM: OpenJDK 64-Bit Server VM (25.144-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libjfxwebkit.so+0x172511b]
#
# Core dump written. Default location: /home/xxx/builds/core or core.5840
#
# An error report file with more information is saved as:
# /home/xxx/builds/hs_err_pid5840.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
[1]    5840 abort (core dumped)  java -jar Lightmod-1.0.5.jar
```

To repo: I went to the chat app template, clicked around a bit, then tried to open the server.clj file. That's when the first crash occurred.

**Comment by oakes** [comment]
The webview may be unstable on linux, though I haven't experienced this on ubuntu. Is it possible for you to install JDK 9? I believe it has an updated webview.

**Comment by RGrun** [comment]
Installed jdk9-openjdk (https://www.archlinux.org/packages/extra/x86_64/jdk9-openjdk/), and now it does not launch at all, with the following command-line error:

```
Error: Could not find or load main class lightmod.core
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```

**Comment by oakes** [comment]
Is there an arch package for openjfx 9? It appears that openjdk doesn't
include javafx so you have to install it separately.

**Comment by RGrun** [comment]
Ahh, sadly there is not. The latest openjfx available in the arch repos is 8.

I guess I'll just have to wait until the maintainer updates it. Thanks for your time.

**Comment by oakes** [comment]
I'm guessing this is no longer an issue -- Lightmod now has a .AppImage with the JDK built in, and a jar version that requires JDK 11 -- so hopefully the webview is more stable on Arch now. If anyone still notices this crash please let me know.
