### ISSUE TITLE
Consider Unlicense

### ISSUE THREAD

**Issue by arichiardi** [oakes/Lightmod#8]
Awesome project!

I am starting to use the [Unlicense](https://unlicense.org/) pretty much everywhere when I don't have any dependency clash :smile: I suggest you to use that instead of the few lines in the README, some company might now use your work unless there is an actual license applied to it.

Apart from that, thanks for your work to the public domain!

**Comment by arichiardi** [comment]
Lol my bad, I have read the README only and did not notice you are using exactly the Unlicense

**Comment by oakes** [comment]
Hah yep I'm a big fan of Unlicense :)
